#!/usr/bin/perl -T -CSDAL

use warnings;
use strict;
use utf8;
use Encode qw/encode/;
use IServ::Conf;
use IServ::DB;
use IServ::Locale;
use MIME::Lite;

IServ::Locale::UseDefLang;

my @lists;
my $text;
my $domain = "unassigned";
my $fn = "/var/lib/iserv/config/config.pm";
$ENV{PATH} = '';

if (-r $fn) {
  require $fn;
  $domain = $conf->{Domain};
}

sub get_lists() {
  @lists = IServ::DB::SelectCol("SELECT recipient FROM mailredirection_addresses WHERE comment = ?", "Hidden Verteiler");
}

sub update_lists() {
  for (my $i = 0; $i < @lists; $i++) {
    my $oldrecipient = $lists[$i];
    my ($recipient) = split(/\+/, $oldrecipient);
    my $randomstr = int(rand(9999)+1);
    my $fullname;
    my $subjecttype;

    my @namecol = IServ::DB::SelectCol "SELECT Name FROM groups WHERE Act = ? LIMIT 1", $recipient;
    if (@namecol < 1) {
      my @firstname = IServ::DB::SelectCol "SELECT Firstname FROM users WHERE Act = ? LIMIT 1", $recipient;
      my @lastname = IServ::DB::SelectCol "SELECT Lastname FROM users WHERE Act = ? LIMIT 1", $recipient; 
      print STDERR "Failed to get first name." unless @firstname > 0;
      exit 1 unless @firstname > 0;
      print STDERR "Failed to get last name." unless @lastname > 0;
      exit 1 unless @lastname > 0;

      $fullname = "$firstname[0] $lastname[0]";
      $subjecttype = _("User");
    } else {
      ($fullname) = @namecol;
      $subjecttype = _("Group");
    }

    IServ::DB::Do "UPDATE mailredirection_addresses SET recipient = ? WHERE recipient = ?", "$recipient+$randomstr", $oldrecipient;

    $text .= sprintf(_("The alias for %s %s I have changed from %s@%s to %s@%s."), $subjecttype, $fullname, $oldrecipient, $domain, $recipient . '+' . $randomstr, $domain)."\n";
  }
}

sub open_msg() {
  $text = _("Dear administrators,") . "\n";
  $text .= "\n";
  $text .= _("I have updated the dynamic aliases. I have changed the following ones:") . "\n";
  $text .= "\n";
}

sub close_msg() {
  $text .= "\n";
  $text .= _("Sincerely yours,")."\n";
  $text .= sprintf(_("root on %s"), $domain)."\n";
}

sub send_mail() {
  my $msg = MIME::Lite->new(
      From	=> "root <root\@$domain>",
      To	=> "Admins <admins\@$domain>",
      Subject	=> encode('MIME-Header', _("Dynamic aliases updated")),
      Type	=> 'multipart/mixed',
  );

  my $part = MIME::Lite->new(
      Type    => 'TEXT',
      Data    => encode('UTF-8', $text),
      Encoding => 'quoted-printable',
  );

  $part->attr('content-type.charset' => 'UTF-8');
  $msg->attach($part);
  $msg->send;
}

get_lists();
open_msg() unless @lists < 1;
update_lists() unless @lists < 1;
close_msg() unless @lists < 1;
send_mail() unless @lists < 1;
